// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRvOQRbIDrqJpUoGneVCv4JuXOYJOsXE',
    appId: '1:422975265:web:40a11b23f3c1e2d44a5060',
    messagingSenderId: '422975265',
    projectId: 'lamhoai-rms',
    authDomain: 'lamhoai-rms.firebaseapp.com',
    databaseURL: 'https://lamhoai-rms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lamhoai-rms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkxRTkMhsNZhK0H6IqRa00jfmBuWhINw',
    appId: '1:422975265:android:5bf04fcaf1f991604a5060',
    messagingSenderId: '422975265',
    projectId: 'lamhoai-rms',
    databaseURL: 'https://lamhoai-rms-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lamhoai-rms.firebasestorage.app',
  );
}
